server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ntudat
    username: postgres
    password: PT@2586151267o
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect